export const SAVE_SERVER_SECCESS = 'SAVE_SERVER_SECCESS';
export const SAVE_SERVER_ERROR = 'SAVE_SERVER_ERROR';
export const GET_SURVEYS_SECCESS = 'GET_SURVEYS_SECCESS';
export const GET_SURVEYS_ERROR = 'GET_SURVEYS_ERROR';
