export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_UNSUCCESS = "SIGN_IN_UNSUCCESS";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_UNSUCCESS = "SIGN_UP_UNSUCCESS";
